project_id = "krmeineyonriifvoexkx"

[functions.request-login]
verify_jwt = false

[functions.verify-login]
verify_jwt = false

[functions.set-user-code]
verify_jwt = true

[functions.list-fiches]
verify_jwt = true

[functions.list-all-fiches]
verify_jwt = true

[functions.request-update]
verify_jwt = true

[functions.admin-login]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.google-auth-setup]
verify_jwt = true

[functions.google-oauth]
verify_jwt = true
