project_id = "krmeineyonriifvoexkx"

[functions.request-login]
verify_jwt = false

[functions.verify-login]
verify_jwt = false

[functions.set-user-code]
verify_jwt = true

[functions.list-fiches]
verify_jwt = true

[functions.request-update]
verify_jwt = true

[functions.verify-admin]
verify_jwt = false

[functions.admin-list-all-fiches]
verify_jwt = false

[functions.admin-update-fiche]
verify_jwt = false

[functions.admin-get-history]
verify_jwt = false
