// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjkhysvttfayoxczzard.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlqa2h5c3Z0dGZheW94Y3p6YXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjIxMTYsImV4cCI6MjA3MjMzODExNn0.mmEiXZNlu5r88uYGOPn2CoTDTRob32RZyoq8pFwYp0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});