// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krmeineyonriifvoexkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtybWVpbmV5b25yaWlmdm9leGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjAzNTQsImV4cCI6MjA3MDU5NjM1NH0.oCi_rDOXeeFjpaXuVq_xfhGDlNywiAFAjFoE9hPcNo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});